STYLES = {
    "FRESH_GRAD": {
        "name": "Fresh Graduate",
        "persona": "mentor",
        "evaluator_mode": "unified",
        "base_competency_priority": {
            "tech_core": "HIGH",
            "tech_data": "HIGH",
            "tech_framework": "MEDIUM",
            "behav_adaptability": "HIGH",
            "behav_teamwork": "MEDIUM",
            "behav_communication": "MEDIUM",
            "cog_problem_solving": "HIGH",
            "cog_analytical": "MEDIUM",
            "cog_learning": "HIGH",
        },
        "evidence_minimums": {
            "tech_core": 2,
            "tech_data": 2,
            "tech_framework": 1,
            "behav_adaptability": 1,
            "behav_teamwork": 1,
            "behav_communication": 1,
            "cog_problem_solving": 2,
            "cog_analytical": 1,
        },
        "evaluator_weights": {
            "technical": 0.35,
            "communication": 0.15,
            "reasoning": 0.25,
            "behavioral": 0.10,
            "confidence": 0.05,
            "completeness": 0.10,
        },
        "max_probe_depth": 1,
        "phase_order": ["intro", "technical", "behavioral", "conclusion"],
        "early_termination_threshold": 0.9,
        "difficulty_range": (1, 2),
        "max_questions": 8,
        "allow_probing": True,
        "hypothesis_count": 5,
    },
    "JUNIOR": {
        "name": "Junior Developer",
        "persona": "friendly",
        "evaluator_mode": "unified",
        "base_competency_priority": {
            "tech_core": "HIGH",
            "tech_framework": "HIGH",
            "tech_testing": "MEDIUM",
            "behav_teamwork": "HIGH",
            "behav_communication": "MEDIUM",
            "cog_problem_solving": "HIGH",
            "cog_analytical": "MEDIUM",
        },
        "evidence_minimums": {
            "tech_core": 2,
            "tech_framework": 2,
            "tech_testing": 1,
            "behav_teamwork": 2,
            "behav_communication": 1,
            "cog_problem_solving": 2,
            "cog_analytical": 1,
        },
        "evaluator_weights": {
            "technical": 0.30,
            "communication": 0.15,
            "reasoning": 0.20,
            "behavioral": 0.15,
            "confidence": 0.10,
            "completeness": 0.10,
        },
        "max_probe_depth": 2,
        "phase_order": ["intro", "technical", "behavioral", "conclusion"],
        "early_termination_threshold": 0.85,
        "difficulty_range": (1, 2),
        "max_questions": 8,
        "allow_probing": True,
        "hypothesis_count": 6,
    },
    "MID_LEVEL": {
        "name": "Mid-Level Developer",
        "persona": "conversational",
        "evaluator_mode": "unified",
        "base_competency_priority": {
            "tech_core": "HIGH",
            "tech_framework": "HIGH",
            "tech_system_design": "HIGH",
            "tech_db": "MEDIUM",
            "tech_testing": "MEDIUM",
            "behav_teamwork": "MEDIUM",
            "behav_leadership": "MEDIUM",
            "cog_problem_solving": "HIGH",
            "cog_decision_making": "MEDIUM",
            "exp_project_depth": "HIGH",
        },
        "evidence_minimums": {
            "tech_core": 2,
            "tech_framework": 2,
            "tech_system_design": 2,
            "tech_db": 1,
            "tech_testing": 1,
            "behav_teamwork": 1,
            "behav_leadership": 1,
            "cog_problem_solving": 2,
            "cog_decision_making": 1,
            "exp_project_depth": 2,
        },
        "evaluator_weights": {
            "technical": 0.30,
            "communication": 0.15,
            "reasoning": 0.20,
            "behavioral": 0.15,
            "confidence": 0.10,
            "completeness": 0.10,
        },
        "max_probe_depth": 3,
        "phase_order": ["intro", "experience", "technical", "behavioral", "conclusion"],
        "early_termination_threshold": 0.85,
        "difficulty_range": (1, 3),
        "max_questions": 12,
        "allow_probing": True,
        "hypothesis_count": 8,
    },
    "SENIOR": {
        "name": "Senior Developer",
        "persona": "formal",
        "evaluator_mode": "unified",
        "base_competency_priority": {
            "tech_system_design": "HIGH",
            "tech_core": "MEDIUM",
            "behav_leadership": "HIGH",
            "cog_decision_making": "HIGH",
            "exp_scaling": "HIGH",
            "exp_project_depth": "HIGH",
            "cog_problem_solving": "MEDIUM",
            "behav_communication": "MEDIUM",
        },
        "evidence_minimums": {
            "tech_system_design": 3,
            "tech_core": 1,
            "behav_leadership": 2,
            "cog_decision_making": 2,
            "exp_scaling": 2,
            "exp_project_depth": 2,
            "cog_problem_solving": 1,
            "behav_communication": 1,
        },
        "evaluator_weights": {
            "technical": 0.30,
            "communication": 0.10,
            "reasoning": 0.25,
            "behavioral": 0.15,
            "confidence": 0.10,
            "completeness": 0.10,
        },
        "max_probe_depth": 3,
        "phase_order": ["intro", "experience", "technical", "behavioral", "conclusion"],
        "early_termination_threshold": 0.80,
        "difficulty_range": (2, 3),
        "max_questions": 12,
        "allow_probing": True,
        "hypothesis_count": 8,
    },
    "TECH_LEAD": {
        "name": "Tech Lead",
        "persona": "formal",
        "evaluator_mode": "unified",
        "base_competency_priority": {
            "behav_leadership": "HIGH",
            "behav_teamwork": "HIGH",
            "tech_system_design": "HIGH",
            "cog_decision_making": "HIGH",
            "behav_conflict": "MEDIUM",
            "exp_scaling": "MEDIUM",
            "exp_project_depth": "MEDIUM",
        },
        "evidence_minimums": {
            "behav_leadership": 3,
            "behav_teamwork": 2,
            "tech_system_design": 2,
            "cog_decision_making": 2,
            "behav_conflict": 1,
            "exp_scaling": 1,
            "exp_project_depth": 1,
        },
        "evaluator_weights": {
            "technical": 0.20,
            "communication": 0.15,
            "reasoning": 0.20,
            "behavioral": 0.25,
            "confidence": 0.10,
            "completeness": 0.10,
        },
        "max_probe_depth": 3,
        "phase_order": ["intro", "experience", "technical", "behavioral", "conclusion"],
        "early_termination_threshold": 0.80,
        "difficulty_range": (2, 3),
        "max_questions": 12,
        "allow_probing": True,
        "hypothesis_count": 8,
    },
    "EM": {
        "name": "Engineering Manager",
        "persona": "formal",
        "evaluator_mode": "unified",
        "base_competency_priority": {
            "behav_leadership": "HIGH",
            "behav_conflict": "HIGH",
            "cog_decision_making": "HIGH",
            "exp_best_practices": "HIGH",
            "behav_communication": "MEDIUM",
            "behav_teamwork": "MEDIUM",
            "tech_system_design": "LOW",
        },
        "evidence_minimums": {
            "behav_leadership": 3,
            "behav_conflict": 2,
            "cog_decision_making": 2,
            "exp_best_practices": 2,
            "behav_communication": 1,
            "behav_teamwork": 1,
        },
        "evaluator_weights": {
            "technical": 0.10,
            "communication": 0.20,
            "reasoning": 0.20,
            "behavioral": 0.30,
            "confidence": 0.10,
            "completeness": 0.10,
        },
        "max_probe_depth": 2,
        "phase_order": ["intro", "experience", "behavioral", "conclusion"],
        "early_termination_threshold": 0.80,
        "difficulty_range": (2, 3),
        "max_questions": 10,
        "allow_probing": True,
        "hypothesis_count": 7,
    },
    "FAANG": {
        "name": "FAANG-Style Interview",
        "persona": "faang",
        "evaluator_mode": "parallel",
        "base_competency_priority": {
            "tech_data": "HIGH",
            "tech_system_design": "HIGH",
            "cog_problem_solving": "HIGH",
            "cog_analytical": "HIGH",
            "tech_core": "MEDIUM",
            "behav_teamwork": "MEDIUM",
        },
        "evidence_minimums": {
            "tech_data": 3,
            "tech_system_design": 3,
            "cog_problem_solving": 3,
            "cog_analytical": 2,
            "tech_core": 1,
            "behav_teamwork": 1,
        },
        "evaluator_weights": {
            "technical": 0.40,
            "communication": 0.10,
            "reasoning": 0.30,
            "behavioral": 0.10,
            "confidence": 0.05,
            "completeness": 0.05,
        },
        "max_probe_depth": 4,
        "phase_order": ["intro", "technical", "behavioral", "conclusion"],
        "early_termination_threshold": 0.75,
        "difficulty_range": (2, 3),
        "max_questions": 6,
        "allow_probing": True,
        "hypothesis_count": 6,
    },
    "FAANG_LITE": {
        "name": "FAANG-Style (Cost-Optimized)",
        "persona": "faang",
        "evaluator_mode": "unified",
        "base_competency_priority": {
            "tech_data": "HIGH",
            "tech_system_design": "HIGH",
            "cog_problem_solving": "HIGH",
            "cog_analytical": "HIGH",
            "tech_core": "MEDIUM",
        },
        "evidence_minimums": {
            "tech_data": 2,
            "tech_system_design": 2,
            "cog_problem_solving": 2,
            "cog_analytical": 2,
            "tech_core": 1,
        },
        "evaluator_weights": {
            "technical": 0.40,
            "communication": 0.10,
            "reasoning": 0.30,
            "behavioral": 0.10,
            "confidence": 0.05,
            "completeness": 0.05,
        },
        "max_probe_depth": 3,
        "phase_order": ["intro", "technical", "behavioral", "conclusion"],
        "early_termination_threshold": 0.80,
        "difficulty_range": (2, 3),
        "max_questions": 8,
        "allow_probing": True,
        "hypothesis_count": 6,
    },
    "STARTUP": {
        "name": "Startup Interview",
        "persona": "conversational",
        "evaluator_mode": "unified",
        "base_competency_priority": {
            "tech_core": "HIGH",
            "tech_framework": "HIGH",
            "behav_adaptability": "HIGH",
            "exp_project_depth": "HIGH",
            "tech_db": "MEDIUM",
            "tech_devops": "MEDIUM",
            "cog_problem_solving": "MEDIUM",
        },
        "evidence_minimums": {
            "tech_core": 2,
            "tech_framework": 2,
            "behav_adaptability": 2,
            "exp_project_depth": 2,
            "tech_db": 1,
            "tech_devops": 1,
            "cog_problem_solving": 1,
        },
        "evaluator_weights": {
            "technical": 0.30,
            "communication": 0.15,
            "reasoning": 0.20,
            "behavioral": 0.15,
            "confidence": 0.10,
            "completeness": 0.10,
        },
        "max_probe_depth": 2,
        "phase_order": ["intro", "experience", "technical", "behavioral", "conclusion"],
        "early_termination_threshold": 0.85,
        "difficulty_range": (1, 3),
        "max_questions": 10,
        "allow_probing": True,
        "hypothesis_count": 7,
    },
    "CONTRACT": {
        "name": "Contractor Interview",
        "persona": "formal",
        "evaluator_mode": "unified",
        "base_competency_priority": {
            "exp_domain": "HIGH",
            "exp_project_depth": "HIGH",
            "behav_communication": "HIGH",
            "tech_core": "MEDIUM",
            "tech_framework": "MEDIUM",
            "exp_best_practices": "MEDIUM",
        },
        "evidence_minimums": {
            "exp_domain": 2,
            "exp_project_depth": 2,
            "behav_communication": 1,
            "tech_core": 1,
            "tech_framework": 1,
            "exp_best_practices": 1,
        },
        "evaluator_weights": {
            "technical": 0.30,
            "communication": 0.20,
            "reasoning": 0.15,
            "behavioral": 0.10,
            "confidence": 0.10,
            "completeness": 0.15,
        },
        "max_probe_depth": 1,
        "phase_order": ["intro", "experience", "technical", "conclusion"],
        "early_termination_threshold": 0.85,
        "difficulty_range": (1, 2),
        "max_questions": 8,
        "allow_probing": False,
        "hypothesis_count": 5,
    },
    "EXECUTIVE": {
        "name": "Executive Interview",
        "persona": "formal",
        "evaluator_mode": "unified",
        "base_competency_priority": {
            "behav_leadership": "HIGH",
            "cog_decision_making": "HIGH",
            "cog_creativity": "HIGH",
            "exp_scaling": "HIGH",
            "behav_communication": "MEDIUM",
            "behav_conflict": "MEDIUM",
        },
        "evidence_minimums": {
            "behav_leadership": 3,
            "cog_decision_making": 3,
            "cog_creativity": 2,
            "exp_scaling": 2,
            "behav_communication": 1,
            "behav_conflict": 1,
        },
        "evaluator_weights": {
            "technical": 0.05,
            "communication": 0.20,
            "reasoning": 0.20,
            "behavioral": 0.30,
            "confidence": 0.15,
            "completeness": 0.10,
        },
        "max_probe_depth": 2,
        "phase_order": ["intro", "experience", "behavioral", "conclusion"],
        "early_termination_threshold": 0.75,
        "difficulty_range": (2, 3),
        "max_questions": 10,
        "allow_probing": True,
        "hypothesis_count": 7,
    },
    "STRESS_TEST": {
        "name": "Stress Test Interview",
        "persona": "stress",
        "evaluator_mode": "unified",
        "base_competency_priority": {
            "behav_adaptability": "HIGH",
            "behav_conflict": "HIGH",
            "cog_problem_solving": "HIGH",
            "tech_core": "MEDIUM",
            "behav_communication": "MEDIUM",
        },
        "evidence_minimums": {
            "behav_adaptability": 3,
            "behav_conflict": 2,
            "cog_problem_solving": 2,
            "tech_core": 1,
            "behav_communication": 1,
        },
        "evaluator_weights": {
            "technical": 0.20,
            "communication": 0.10,
            "reasoning": 0.20,
            "behavioral": 0.30,
            "confidence": 0.10,
            "completeness": 0.10,
        },
        "max_probe_depth": 3,
        "phase_order": ["intro", "technical", "behavioral", "conclusion"],
        "early_termination_threshold": 0.80,
        "difficulty_range": (2, 3),
        "max_questions": 8,
        "allow_probing": True,
        "hypothesis_count": 6,
    },
    "STANDARD": {
        "name": "Standard Interview",
        "persona": "friendly",
        "evaluator_mode": "unified",
        "base_competency_priority": {
            "tech_core": "HIGH",
            "tech_framework": "MEDIUM",
            "behav_teamwork": "MEDIUM",
            "behav_communication": "MEDIUM",
            "cog_problem_solving": "HIGH",
            "cog_analytical": "MEDIUM",
            "exp_project_depth": "MEDIUM",
            "tech_db": "MEDIUM",
            "tech_testing": "LOW",
            "behav_adaptability": "LOW",
        },
        "evidence_minimums": {
            "tech_core": 2,
            "tech_framework": 1,
            "behav_teamwork": 1,
            "behav_communication": 1,
            "cog_problem_solving": 2,
            "cog_analytical": 1,
            "exp_project_depth": 1,
            "tech_db": 1,
            "tech_testing": 1,
            "behav_adaptability": 1,
        },
        "evaluator_weights": {
            "technical": 0.30,
            "communication": 0.15,
            "reasoning": 0.20,
            "behavioral": 0.15,
            "confidence": 0.10,
            "completeness": 0.10,
        },
        "max_probe_depth": 2,
        "phase_order": ["intro", "experience", "technical", "behavioral", "conclusion"],
        "early_termination_threshold": 0.85,
        "difficulty_range": (1, 3),
        "max_questions": 10,
        "allow_probing": True,
        "hypothesis_count": 6,
    },
}

PERSONAS = ["friendly", "formal", "strict", "faang", "conversational", "stress", "mentor"]

EVALUATOR_MODES = ["unified", "parallel"]

DEFAULT_STYLE = "STANDARD"


def get_style(name: str = None) -> dict:
    if name is None:
        name = DEFAULT_STYLE
    style = STYLES.get(name.upper())
    if style is None:
        style = STYLES[DEFAULT_STYLE]
    return dict(style)


def list_styles() -> list:
    return [
        {
            "name": name,
            "display_name": style["name"],
            "persona": style["persona"],
            "evaluator_mode": style["evaluator_mode"],
            "max_questions": style["max_questions"],
        }
        for name, style in sorted(STYLES.items())
    ]


def get_persona(name: str = None) -> str:
    return get_style(name).get("persona", "friendly")


def get_evaluator_mode(name: str = None) -> str:
    return get_style(name).get("evaluator_mode", "unified")
