"""v2 fresh schema

Revision ID: 5d045fd43882
Revises: 
Create Date: 2026-07-22 21:12:18.218457
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d045fd43882'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('resume_url', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('google_id', sa.Text(), nullable=True),
    sa.Column('is_registered', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_candidate_email', 'candidate_profiles', ['email'], unique=False)
    op.create_index('idx_candidate_google', 'candidate_profiles', ['google_id'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('settings', sa.Text(), server_default='{}', nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_orgs_slug', 'organizations', ['slug'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('resource_type', sa.Text(), nullable=True),
    sa.Column('resource_id', sa.Text(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_action', 'audit_log', ['action'], unique=False)
    op.create_index('idx_audit_created', 'audit_log', ['created_at'], unique=False)
    op.create_index('idx_audit_org', 'audit_log', ['org_id'], unique=False)
    op.create_index('idx_audit_user', 'audit_log', ['user_id'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_companies_org', 'companies', ['org_id'], unique=False)
    op.create_table('interview_slots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('duration_min', sa.Integer(), server_default='45', nullable=False),
    sa.Column('buffer_min', sa.Integer(), server_default='5', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_slots_org', 'interview_slots', ['org_id'], unique=False)
    op.create_table('org_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("role IN ('owner','member','viewer')", name='org_users_role_check'),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_org_users_org', 'org_users', ['org_id'], unique=False)
    op.create_index('idx_org_users_user', 'org_users', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate_invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('candidate_email', sa.Text(), nullable=False),
    sa.Column('candidate_name', sa.Text(), nullable=False),
    sa.Column('job_role', sa.Text(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('interview_config', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("status IN ('pending','accepted','completed','expired')", name='invitations_status_check'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index('idx_invitations_company', 'candidate_invitations', ['company_id'], unique=False)
    op.create_index('idx_invitations_token', 'candidate_invitations', ['token'], unique=False)
    op.create_table('company_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('document_type', sa.Text(), server_default='pdf', nullable=False),
    sa.Column('pinecone_namespace', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='company_documents_company_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_documents_company', 'company_documents', ['company_id'], unique=False)
    op.create_table('interview_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('candidate_profile_id', sa.UUID(), nullable=True),
    sa.Column('job_role', sa.Text(), nullable=False),
    sa.Column('session_type', sa.Text(), server_default='company', nullable=True),
    sa.Column('interaction_mode', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='active', nullable=True),
    sa.Column('current_phase', sa.Text(), server_default='intro', nullable=True),
    sa.Column('current_question_number', sa.Integer(), server_default='0', nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('final_score', sa.Numeric(), nullable=True),
    sa.Column('final_feedback', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='interview_sessions_company_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sessions_company', 'interview_sessions', ['company_id'], unique=False)
    op.create_index('idx_sessions_final_score', 'interview_sessions', ['final_score'], unique=False, postgresql_where='final_score IS NOT NULL')
    op.create_index('idx_sessions_org', 'interview_sessions', ['org_id'], unique=False)
    op.create_index('idx_sessions_started_at', 'interview_sessions', ['started_at'], unique=False)
    op.create_index('idx_sessions_status', 'interview_sessions', ['status'], unique=False)
    op.create_table('interview_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('job_role', sa.Text(), nullable=False),
    sa.Column('total_questions', sa.Integer(), server_default='10', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='interview_templates_company_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slot_availability',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slot_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_booked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['slot_id'], ['interview_slots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_availability_slot_date', 'slot_availability', ['slot_id', 'date'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slot_id', sa.UUID(), nullable=False),
    sa.Column('availability_id', sa.UUID(), nullable=False),
    sa.Column('candidate_email', sa.Text(), nullable=False),
    sa.Column('candidate_name', sa.Text(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Text(), server_default='confirmed', nullable=False),
    sa.Column('confirmation_sent', sa.Boolean(), nullable=False),
    sa.Column('booked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("status IN ('confirmed','completed','cancelled','no-show')", name='bookings_status_check'),
    sa.ForeignKeyConstraint(['availability_id'], ['slot_availability.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['slot_id'], ['interview_slots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_candidate_sessions_candidate', 'candidate_sessions', ['candidate_id'], unique=False)
    op.create_index('idx_candidate_sessions_session', 'candidate_sessions', ['session_id'], unique=False)
    op.create_table('interview_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('message_type', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('question_number', sa.Integer(), server_default='0', nullable=True),
    sa.Column('phase', sa.Text(), nullable=True),
    sa.Column('score', sa.Numeric(), nullable=True),
    sa.Column('follow_up_question', sa.Text(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], name='interview_messages_session_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_session', 'interview_messages', ['session_id'], unique=False)
    op.create_table('public_interviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('interview_mode', sa.Text(), server_default='typing', nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('verification_method', sa.Text(), server_default='none', nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_candidates', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['interview_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index('idx_public_interviews_org', 'public_interviews', ['org_id'], unique=False)
    op.create_index('idx_public_interviews_token', 'public_interviews', ['token'], unique=False)
    op.create_table('interview_evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Numeric(), nullable=True),
    sa.Column('technical_score', sa.Numeric(), nullable=True),
    sa.Column('communication_score', sa.Numeric(), nullable=True),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('weaknesses', sa.Text(), nullable=True),
    sa.Column('feedback_detail', sa.Text(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('score >= 0 AND score <= 10', name='interview_evaluations_score_check'),
    sa.ForeignKeyConstraint(['message_id'], ['interview_messages.id'], name='interview_evaluations_message_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], name='interview_evaluations_session_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_evaluations_session_id', 'interview_evaluations', ['session_id'], unique=False)
    op.create_table('public_interview_submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('candidate_email', sa.Text(), nullable=False),
    sa.Column('candidate_name', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['public_id'], ['public_interviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_submissions_public', 'public_interview_submissions', ['public_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_submissions_public', table_name='public_interview_submissions')
    op.drop_table('public_interview_submissions')
    op.drop_index('idx_evaluations_session_id', table_name='interview_evaluations')
    op.drop_table('interview_evaluations')
    op.drop_index('idx_public_interviews_token', table_name='public_interviews')
    op.drop_index('idx_public_interviews_org', table_name='public_interviews')
    op.drop_table('public_interviews')
    op.drop_index('idx_messages_session', table_name='interview_messages')
    op.drop_table('interview_messages')
    op.drop_index('idx_candidate_sessions_session', table_name='candidate_sessions')
    op.drop_index('idx_candidate_sessions_candidate', table_name='candidate_sessions')
    op.drop_table('candidate_sessions')
    op.drop_table('bookings')
    op.drop_index('idx_availability_slot_date', table_name='slot_availability')
    op.drop_table('slot_availability')
    op.drop_table('interview_templates')
    op.drop_index('idx_sessions_status', table_name='interview_sessions')
    op.drop_index('idx_sessions_started_at', table_name='interview_sessions')
    op.drop_index('idx_sessions_org', table_name='interview_sessions')
    op.drop_index('idx_sessions_final_score', table_name='interview_sessions', postgresql_where='final_score IS NOT NULL')
    op.drop_index('idx_sessions_company', table_name='interview_sessions')
    op.drop_table('interview_sessions')
    op.drop_index('idx_documents_company', table_name='company_documents')
    op.drop_table('company_documents')
    op.drop_index('idx_invitations_token', table_name='candidate_invitations')
    op.drop_index('idx_invitations_company', table_name='candidate_invitations')
    op.drop_table('candidate_invitations')
    op.drop_table('refresh_tokens')
    op.drop_index('idx_org_users_user', table_name='org_users')
    op.drop_index('idx_org_users_org', table_name='org_users')
    op.drop_table('org_users')
    op.drop_index('idx_slots_org', table_name='interview_slots')
    op.drop_table('interview_slots')
    op.drop_index('idx_companies_org', table_name='companies')
    op.drop_table('companies')
    op.drop_index('idx_audit_user', table_name='audit_log')
    op.drop_index('idx_audit_org', table_name='audit_log')
    op.drop_index('idx_audit_created', table_name='audit_log')
    op.drop_index('idx_audit_action', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('users')
    op.drop_index('idx_orgs_slug', table_name='organizations')
    op.drop_table('organizations')
    op.drop_index('idx_candidate_google', table_name='candidate_profiles')
    op.drop_index('idx_candidate_email', table_name='candidate_profiles')
    op.drop_table('candidate_profiles')
    # ### end Alembic commands ###
