"""make interview_sessions.company_id nullable

Revision ID: cb0990d55c7d
Revises: 5d045fd43882
Create Date: 2026-07-23 00:45:32.703745
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb0990d55c7d'
down_revision: Union[str, None] = '5d045fd43882'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interview_sessions', 'company_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_constraint(op.f('interview_sessions_company_id_fkey'), 'interview_sessions', type_='foreignkey')
    op.create_foreign_key('interview_sessions_company_id_fkey', 'interview_sessions', 'companies', ['company_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('interview_sessions_company_id_fkey', 'interview_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('interview_sessions_company_id_fkey'), 'interview_sessions', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.alter_column('interview_sessions', 'company_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
